#!/bin/sh
while read file
do 
	fullpath="$(pwd)/$file"
	case "$1" in
		"s")
			new_name=$(echo $RANDOM | md5sum | head -c 20;echo)
			cp $file $HOME/Pictures/$new_name
		;;
		"w")
			cp $file $HOME/Pictures/wallPaper
			feh --bg-scale $HOME/Pictures/wallPaper
		;;
	esac
done
